version: '3.9'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb

    ports:
      - "8086:8086"

    volumes:
      - influxdb-data:/var/lib/influxdb2

    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: geheim123
      DOCKER_INFLUXDB_INIT_ORG: MyOrg
      DOCKER_INFLUXDB_INIT_BUCKET: Sensors
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-secret-token

volumes:
  influxdb-data:
  