syntax = "proto3";

option csharp_namespace = "IngestionService.Trip";

import "google/protobuf/timestamp.proto";

package trip;

service TripService {
  rpc StartTrip (StartTripRequest) returns (StartTripResponse);
  rpc EndTrip (EndTripRequest) returns (EndTripResponse);
}

message StartTripRequest {
  string telemetry_unit_id = 1;
  google.protobuf.Timestamp start_timestamp = 2;
}

message StartTripResponse {
  string trip_id = 1;
}

message EndTripRequest {
  string telemetry_unit_id = 1;
  google.protobuf.Timestamp end_timestamp = 2;
  // Nur gesetzt, falls der ursprüngliche StartTrip-Call fehlgeschlagen ist.
  // Wird verwendet, um den Trip nachträglich mit Start- und Endzeitpunkt anzulegen.
  google.protobuf.Timestamp start_timestamp = 3;
}

message EndTripResponse {
  string trip_id = 1;
}
