<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FleetControlServer.Data\FleetControlServer.Data.csproj" />
    <ProjectReference Include="..\FleetControlServer.Domain\FleetControlServer.Domain.csproj" />
    <ProjectReference Include="..\FleetControlServer.Infra\FleetControlServer.Infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageReference Include="Grpc.Tools" Version="2.80.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\telemetry.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\assignment_updates.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
