services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    
    ports:
      - "5672:5672"
      - "15672:15672"
    
    environment:
      RABBITMQ_DEFAULT_USER: rabbit-mq-user
      RABBITMQ_DEFAULT_PASS: rabbit-mq-pw

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
