// <auto-generated />
using System;
using FleetControlServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetControlServer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802181052_AddPersonAndDriversLicenses")]
    partial class AddPersonAndDriversLicenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetControlServer.Domain.DriversLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LicenseType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ObtainedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("VehicleDriverId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleDriverId");

                    b.ToTable("DriversLicenses");
                });

            modelBuilder.Entity("FleetControlServer.Domain.TelemetryUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("TelemetryUnits");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TelemetryUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelemetryUnitId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FirstRegistration")
                        .HasColumnType("date");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PowerPs")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredLicense")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VehicleDriverId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstRegistration")
                        .IsUnique();

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.HasIndex("LicensePlateNumber")
                        .IsUnique();

                    b.HasIndex("VehicleDriverId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("FleetControlServer.Domain.VehicleDriver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleDrivers");
                });

            modelBuilder.Entity("FleetControlServer.Domain.DriversLicense", b =>
                {
                    b.HasOne("FleetControlServer.Domain.VehicleDriver", "VehicleDriver")
                        .WithMany("Licenses")
                        .HasForeignKey("VehicleDriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleDriver");
                });

            modelBuilder.Entity("FleetControlServer.Domain.TelemetryUnit", b =>
                {
                    b.HasOne("FleetControlServer.Domain.Vehicle", "Vehicle")
                        .WithOne("TelemetryUnit")
                        .HasForeignKey("FleetControlServer.Domain.TelemetryUnit", "VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Trip", b =>
                {
                    b.HasOne("FleetControlServer.Domain.TelemetryUnit", "TelemetryUnit")
                        .WithMany()
                        .HasForeignKey("TelemetryUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TelemetryUnit");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Vehicle", b =>
                {
                    b.HasOne("FleetControlServer.Domain.VehicleDriver", "VehicleDriver")
                        .WithMany()
                        .HasForeignKey("VehicleDriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VehicleDriver");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Vehicle", b =>
                {
                    b.Navigation("TelemetryUnit");
                });

            modelBuilder.Entity("FleetControlServer.Domain.VehicleDriver", b =>
                {
                    b.Navigation("Licenses");
                });
#pragma warning restore 612, 618
        }
    }
}
