// <auto-generated />
using System;
using FleetControlServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetControlServer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetControlServer.Domain.TelemetryUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("TelemetryUnits");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TelemetryUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelemetryUnitId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicensePlateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VehicleDriverId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.HasIndex("LicensePlateNumber")
                        .IsUnique();

                    b.HasIndex("VehicleDriverId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("FleetControlServer.Domain.VehicleDriver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleDrivers");
                });

            modelBuilder.Entity("FleetControlServer.Domain.TelemetryUnit", b =>
                {
                    b.HasOne("FleetControlServer.Domain.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Trip", b =>
                {
                    b.HasOne("FleetControlServer.Domain.TelemetryUnit", "TelemetryUnit")
                        .WithMany()
                        .HasForeignKey("TelemetryUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TelemetryUnit");
                });

            modelBuilder.Entity("FleetControlServer.Domain.Vehicle", b =>
                {
                    b.HasOne("FleetControlServer.Domain.VehicleDriver", "VehicleDriver")
                        .WithMany()
                        .HasForeignKey("VehicleDriverId");

                    b.Navigation("VehicleDriver");
                });
#pragma warning restore 612, 618
        }
    }
}
